# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: MULESOFT API BUILD & DEPLOYMENT

on:
  push:
    branches: 
     - master # For Prod environment after release it will deploy the PreProd also
     - develop # For Dev/QA environment
     - 'release/*' # For Stage Environment &  PreProd also
     - 'hotfix/*' #  For Preprod environment
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened]

jobs:

  Munit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven to create Greeter and Mortal contract
      run: mvn web3j:generate-sources --file pom.xml
    - name: Build and analyze
      env:
        GITHUB_TOKEN: ${{ secrets.NEW_GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
    - uses: actions/checkout@v2
      # this is the new step
    - uses: toko-bifrost/ms-teams-deploy-card@master #  or "./" if in a local set-up
      if: always()
      with:
        github-token: ${{ github.token }}
        webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
        timezone: Asia/Kolkata
        environment: Munit
  Sonar:
    runs-on: ubuntu-latest
    needs: [Munit]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
#    - name: Build with Maven to create Greeter and Mortal contract
#      run: mvn web3j:generate-sources --file pom.xml
    - uses: actions/checkout@v2
      # this is the new step
    - uses: toko-bifrost/ms-teams-deploy-card@master #  or "./" if in a local set-up
      if: always()
      with:
        github-token: ${{ github.token }}
        webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
        timezone: Asia/Kolkata
        environment: Sonar
